#!/bin/bash

BAKSMALI="java -jar baksmali-2.2.1.jar"
SMALI="java -jar smali-2.2.1.jar"
CFR="java -jar cfr_0_123.jar"
APKTOOL="java -jar apktool_2.3.0.jar"
ENJARIFY="./enjarify/enjarify.sh"

THREADS="6" # min 2 required

SYSTEM="./system"
OUT="./out"
